services:
  shikimori-bot:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: shiki
    working_dir: /app
    volumes:
      - ./src:/app/src
    command: [".Shiki/bin/python", "src/main.py"]