[project]
name = "shikibot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiocache>=0.12.3",
    "aiogram>=3.22.0",
    "aiohttp>=3.12.15",
    "dotenv>=0.9.9",
]
